# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

        # My locally tested versions:
        # npm --version
        # 6.4.1
        # python --version
        # Python 2.7.12
        # source ifarms/bin/activate
        # python --versionPython 3.5.2


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            # old:
            #python3 -m venv ifarms
            #. ifarms/bin/activate
            # #pip install -r requirements.txt
            #bin/reinstall.sh
                # new cleaner
                ./bin/preinstall.sh
                ./bin/reinstall.sh
                # # source ifarms/bin/activate   # not necessary because source is done in start_service.sh
                #./bin/start_service.sh &
                #./bin/test_api.sh
      - save_cache:
          paths:
            - ./ifarms
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            #old
            #. ifarms/bin/activate
            ## python manage.py test
            #python tests/test.py
            #bin/test_api.sh
                #new:
                 # source ifarms/bin/activate   # not necessary because source is done in start_service.sh
                ./bin/start_service.sh &
                ./bin/test_api.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports
